SEED: 7
DEBUG: False
LOG_FREQ: 100
SAVE_CHECKPOINTS: [5, 10, 15, 20]
INFERENCE_CHECKPOINT: 0

TRAINER:
  LR: 1e-4
  BATCH_SIZE: 8
  EPOCHS: 20
  OPTIMIZER: 'adamw'

MODEL:
  TYPE: 'resnet'
  SIZE: 18
  PRETRAINED: True
  OUT_CHANNELS: 1
  IN_CHANNELS: 3
  LOSS_TYPE: 'L2'

DATALOADER:
  FEATURES: ['vhr']
  LOG_POP: False
  NUM_WORKER: 8
  SHUFFLE: True
  PATCH_SIZE: 200
  VHR_MAX_REFLECTANCE: 5_000
  VHR_BAND_INDICES: [0, 1, 2]
  S2_BAND_INDICES: [2, 1, 0]
  INCLUDE_UNLABELED: False

DATASET:
  CITY_SPLIT: False
  LABELED_CITIES: ['dakar']
  TRAINING: ['dakar']
  TEST: []

AUGMENTATION:
  RANDOM_FLIP: True
  RANDOM_ROTATE: True
  COLOR_SHIFT: False
  GAMMA_CORRECTION: False
  DOWNSAMPLING: 1

CONSISTENCY_TRAINER:
  LOSS_FACTOR: 0.1
  WEIGHT_DECAY: 0.998
  CONSISTENCY_LOSS_TYPE: 'JaccardLikeLoss'