SEED: 7
DEBUG: True
LOG_FREQ: 100
SAVE_CHECKPOINTS: [5, 10, 15]
INFERENCE_CHECKPOINT: 0

MODEL:
  TYPE: 'resnet18'
  PRETRAINED: True
  OUT_CHANNELS: 1
  IN_CHANNELS: 4
  LOSS_TYPE: 'L2'

DATALOADER:
  NUM_WORKER: 8
  SHUFFLE: True
  REFLECTANCE_MAX: 5_000
  SATELLITE_BANDS: [0, 1, 2]
  INCLUDE_UNLABELED: False
  RES_DOWNSAMPLING: 2

DATASET:
  CITY_SPLIT: False
  LABELED_CITIES: ['dakar']
  TRAINING: ['dakar']
  TEST: []

TRAINER:
  LR: 1e-4
  BATCH_SIZE: 8
  EPOCHS: 20
  OPTIMIZER: 'adamw'

AUGMENTATION:
  RANDOM_FLIP: True
  RANDOM_ROTATE: True
  COLOR_SHIFT: False
  GAMMA_CORRECTION: False
  DOWNSAMPLING: 2

CONSISTENCY_TRAINER:
  LOSS_FACTOR: 0.1
  WEIGHT_DECAY: 0.998
  CONSISTENCY_LOSS_TYPE: 'JaccardLikeLoss'