_BASE_: "base.yaml"
DEBUG: False
INFERENCE_CHECKPOINT: 20

MODEL:
  TYPE: 'densenet'
  SIZE: 121
  IN_CHANNELS: 4

DATALOADER:
  FEATURES: ['s2']
  NUM_WORKER: 8
  SHUFFLE: True
  S2_BAND_INDICES: [2, 1, 0, 6]

