SEED: 7
DEBUG: True
LOG_FREQ: 1000
SAVE_CHECKPOINTS: [ 20 ]
INFERENCE_CHECKPOINT: 20

TRAINER:
  LR: 1e-4
  BATCH_SIZE: 8
  EPOCHS: 20
  OPTIMIZER: 'adamw'

MODEL:
  DUALSTREAM: False
  TYPE: 'resnet'
  SIZE: 18
  PRETRAINED: True
  OUT_CHANNELS: 1
  IN_CHANNELS: 4
  LOSS_TYPE: 'L2'

DATALOADER:
  FEATURES: ['s2']
  FEATURE_STREAM1: 's2'
  FEATURE_STREAM2: 's2'
  LOG_POP: False
  NUM_WORKER: 2
  SHUFFLE: True
  PATCH_SIZE: 200
  VHR_MAX_REFLECTANCE: 5_000
  VHR_BAND_INDICES: [ 0, 1, 2 ]
  S2_BAND_INDICES: [ 2, 1, 0, 3 ]
  INCLUDE_UNLABELED: True

DATASET:
  LABELED_CITIES: [ 'dakar' ]
  UNLABELED_CITIES: [ 'nairobi', 'daressalaam' ]
  CENSUS_EVALUATION_CITIES: [ 'dakar', 'nairobi', 'daressalaam', 'ouagadougou' ]

AUGMENTATION:
  RANDOM_FLIP: False
  RANDOM_ROTATE: False
  COLOR_SHIFT: False
  GAMMA_CORRECTION: False
  DOWNSAMPLING: 1
  STREAM1:
    RANDOM_FLIP: True
    RANDOM_ROTATE: True
    COLOR_SHIFT: False
    GAMMA_CORRECTION: False
    DOWNSAMPLING: 1
  STREAM2:
    RANDOM_FLIP: True
    RANDOM_ROTATE: True
    COLOR_SHIFT: False
    GAMMA_CORRECTION: False
    DOWNSAMPLING: 1

CONSISTENCY_TRAINER:
  LOSS_FACTOR: 0.5
  WEIGHT_DECAY: 0.998
  LOSS_TYPE: 'L2'