_BASE_: "base.yaml"
DEBUG: True
INFERENCE_CHECKPOINT: 0

MODEL:
  TYPE: 'resnet18'
  PRETRAINED: True

DATALOADER:
  NUM_WORKER: 8
  SHUFFLE: True
  REFLECTANCE_MAX: 5_000
  SATELLITE_BANDS: [0, 1, 2, 3]