_BASE_: "base.yaml"
DEBUG: False
SAVE_CHECKPOINTS: [10, 20, 30, 40]
INFERENCE_CHECKPOINT: 40

TRAINER:
  BATCH_SIZE: 16
  EPOCHS: 40

MODEL:
  TYPE: 'resnet50'

DATALOADER:
  FEATURES: ['vhr']
  VHR_MAX_REFLECTANCE: 5_000
  VHR_BAND_INDICES: [0, 1, 2]

