_BASE_: "dual_base.yaml"
DEBUG: False

MODEL:
  STREAM1:
    IN_CHANNELS: 4
  STREAM2:
    IN_CHANNELS: 1

DATALOADER:
  FEATURE_STREAM1: 's2'
  FEATURE_STREAM2: 'bf'
  S2_BAND_INDICES: [ 2, 1, 0, 3 ]

DATASET:
  LABELED_CITIES: [ 'dakar' ]
  CENSUS_EVALUATION_CITIES: [ 'dakar', 'nairobi', 'daressalaam' ]
  
  AUGMENTATION:
    STREAM1:
      GAMMA_CORRECTION: True
    STREAM2:
      GAMMA_CORRECTION: False