_BASE_: "da_base.yaml"
DEBUG: False

MODEL:
  STREAM1:
    IN_CHANNELS: 4
  STREAM2:
    IN_CHANNELS: 1

DATALOADER:
  FEATURE_STREAM1: 's2'
  FEATURE_STREAM2: 'bf'
  S2_BAND_INDICES: [ 2, 1, 0, 3 ]
  INCLUDE_UNLABELED: True

DATASET:
  LABELED_CITIES: [ 'dakar' ]
  UNLABELED_CITIES: [ 'nairobi', 'daressalaam' ]
  CENSUS_EVALUATION_CITIES: [ 'dakar', 'nairobi', 'daressalaam', 'ouagadougou' ]
