_BASE_: "base.yaml"
DEBUG: False

MODEL:
  IN_CHANNELS: 4
  MULTI_TASK: True

DATALOADER:
  FEATURES: [ 's2' ]
  S2_BAND_INDICES: [ 2, 1, 0, 3 ]

DATASET:
  LABELED_CITIES: [ 'dakar' ]
  CENSUS_EVALUATION_CITIES: [ 'dakar', 'nairobi', 'daressalaam', 'ouagadougou' ]