_BASE_: "da_base.yaml"
DEBUG: False

MODEL:
  STREAM1:
    IN_CHANNELS: 4
  STREAM2:
    IN_CHANNELS: 1
  DISABLE_FUSION_LOSS: True

DATALOADER:
  FEATURE_STREAM1: 's2'
  FEATURE_STREAM2: 'bf'
  S2_BAND_INDICES: [ 2, 1, 0, 3 ]
  INCLUDE_UNLABELED: True

DATASET:
  LABELED_CITIES: [ 'dakar' ]
  UNLABELED_CITIES: [ 'nairobi', 'daressalaam', 'ouagadougou', 'ndjamena']
  CENSUS_EVALUATION_CITIES: [ 'dakar', 'nairobi', 'daressalaam', 'ouagadougou' ]

CONSISTENCY_TRAINER:
  LOSS_FACTOR: 0.25
  LOSS_TYPE: 'L2'